apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -dev
namespace: ekl-dev
commonLabels:
  app: ekl-frontend
patches:
  - path: deployment-dev.yaml
  - path: virtualservice-dev.yaml
  - path: service-dev.yaml
images:
  - name: ekl-frontend
    newName: ponyworld/ekl-frontend-dev
    newTag: {{IMAGE_TAG}}
